import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";
import { radius, typography } from "../../theme/spacing";

// Shared by the plan feature's three sheets — PartnerPicker, EditSheet and
// AddSheet. They were one stylesheet (`makeSs`) when all three lived in
// app/plan.tsx; keeping them together preserves that sharing.
export const makeSs = (s: (n: number) => number) => StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "flex-end",
  },
  dismiss: { flex: 1 },
  sheet: {
    backgroundColor: colors.card,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 28,
    maxHeight: "88%",
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  sheetTitle: { ...typography.screenTitle, fontSize: s(18), color: colors.text },

  fieldLabel: {
    fontSize: s(11),
    color: colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    fontWeight: "600",
    marginTop: 14,
    marginBottom: 6,
  },
  input: {
    fontSize: s(15),
    color: colors.text,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: colors.background,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  stepperRow: { flexDirection: "row", alignItems: "center", gap: 14 },
  stepperBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  stepperValue: {
    fontSize: s(18),
    fontWeight: "600",
    color: colors.text,
    minWidth: 24,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  segmentedNative: { marginBottom: 4 },
  saveBtn: {
    marginTop: 20,
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: radius.card,
    alignItems: "center",
  },
  saveBtnText: { color: "#FFFFFF", fontSize: s(15), fontWeight: "600" },

  deleteDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
    marginTop: 20,
    marginBottom: 12,
  },
  deleteBtn: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.red + "40",
    backgroundColor: colors.red + "12",
    alignItems: "center",
  },
  deleteBtnText: { fontSize: s(14), fontWeight: "600", color: colors.red },
  deleteBtnSub: { fontSize: s(11), color: colors.red + "AA", marginTop: 2 },

  pillRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  pill: {
    paddingVertical: 6,
    paddingHorizontal: 11,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  pillText: { fontSize: s(12), color: colors.textSecondary, fontWeight: "500" },

  modeToggleNative: { marginBottom: 16 },
  listContainer: {
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    overflow: "hidden",
    marginBottom: 4,
  },
  libraryRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 11,
    paddingHorizontal: 14,
    backgroundColor: colors.background,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  libraryRowSelected: { backgroundColor: colors.primary + "18" },
  libraryRowName: { fontSize: s(14), color: colors.text, fontWeight: "500" },
  libraryRowNameSelected: { color: colors.primary, fontWeight: "600" },
  libraryRowMeta: { fontSize: s(12), color: colors.textSecondary, marginTop: 2 },
  checkBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  checkText: { color: "#FFFFFF", fontSize: s(12), fontWeight: "700" },
  emptyText: {
    color: colors.textMuted,
    fontSize: s(13),
    textAlign: "center",
    paddingVertical: 16,
    lineHeight: 18,
  },

  selectedBanner: {
    backgroundColor: colors.primary + "18",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.primary + "40",
  },
  selectedBannerText: {
    fontSize: s(15),
    fontWeight: "600",
    color: colors.primary,
  },
  selectedBannerSub: {
    fontSize: s(12),
    color: colors.textSecondary,
    marginTop: 2,
  },

  // Superset partner section
  partnerHeader: {
    marginTop: 16,
    marginBottom: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  partnerHeaderText: {
    fontSize: s(11),
    fontWeight: "600",
    color: colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  partnerBadge: {
    backgroundColor: colors.primary + "20",
    borderRadius: 6,
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.primary + "50",
  },
  partnerBadgeText: { fontSize: s(11), color: colors.primary, fontWeight: "600" },
  partnerHint: {
    fontSize: s(12),
    color: colors.warning,
    marginTop: 8,
    textAlign: "center",
  },
});
